"""add game state tables

Revision ID: 6a701a3f1bae
Revises: 0fdff4263d49
Create Date: 2026-05-07 13:27:49.455109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a701a3f1bae'
down_revision = '0fdff4263d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_game_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_word_id', sa.Integer(), nullable=False),
    sa.Column('guessed_letters', sa.String(length=26), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('time_left', sa.Integer(), nullable=True),
    sa.Column('hangman_state', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_word_id'], ['daily_words.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_game_states', schema=None) as batch_op:
        batch_op.create_index('ix_daily_state_user_word', ['user_id', 'daily_word_id'], unique=False)

    op.create_table('unlimited_game_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('guessed_letters', sa.String(length=26), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time_left', sa.Integer(), nullable=True),
    sa.Column('hangman_state', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('unlimited_game_states')
    with op.batch_alter_table('daily_game_states', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_state_user_word')

    op.drop_table('daily_game_states')
    # ### end Alembic commands ###
